// client/src/components/Url.tsx
import React, {FunctionComponent, } from 'react'

export type UrlProps =  {
  shortUrl: string,
  id: string,
  originalUrl: string,
  shortUrlHash: string,
  handleDelete(url: string): void
}

const Url: FunctionComponent<UrlProps> = ({ id, originalUrl, shortUrl, handleDelete }) => {

  const handleDeleteUrl = () => {
    handleDelete(id)
  }

  return (
      <tr className="link">
      <td>
        {originalUrl}
      </td>
      <td data-testid="url-short">
        {shortUrl}<button className='copy-clipboard'>copy</button>
      </td>
      <td>
        <button className='delete-one' onClick={handleDeleteUrl}>Delete</button>
      </td>
    </tr>
  )
}

export default Url

// vue-client/src/components/Url.vue
<template>
  <tr>
    <td>{{ originalUrl }}</td>
    <td>{{ shortUrl }}
      <button @click="handleCopyClipboard">Copy</button>
    </td>
    <td>
      <button @click="handleDeleteUrl">Delete </button>
    </td>
  </tr>
</template>

<script>
export default {
  props: {
    shortUrl: {
      type: String,
      required: true
    },
    id: {
      type: String,
      required: true
    },
    originalUrl: {
      type: String,
      required: true
    },
    shortUrlHash: {
      type: String,
      required: true
    },
    handleDelete: {
      type: String,
      required: true
    }
  },
  name: 'Url',
  data: function() {
    return {

    }
  },
  methods: {
    handleDeleteUrl: function() {
      this.handleDelete(this.id)
    },

    handleCopyClipboard: function() {
      navigator.clipboard.writeText(this.shortUrl)
      alert('copied to clipboard')
    }
  }
}
</script>

<style scoped>

</style>
