// client/src/components/UrlList.tsx
import React, { FunctionComponent } from 'react'
import Url from './Url'

export type UrlListProps = {
  urls :  {
    _id: string,
    shortUrl: string,
    originalUrl: string,
    shortUrlHash: string
  }[],
  error: string,
  handleDelete(url: string): void
}

const UrlList : FunctionComponent<UrlListProps> = ({urls, error, handleDelete}) => {
  return (
    <div>
      {urls.length === 0 ? <p data-testid="no-urls">Start shortening your urls</p> : <p data-testid="urls-all">Here are your shortened urls</p>}
      {error !== '' && <p data-testid="error">{error}</p>}
     
      <table>
        <thead>
          <tr>
            <td>Original Url</td>
            <td>Shortened Url</td>
            <td>Action</td>
          </tr>
        </thead>
        <tbody>
          {urls.map((url) => (
            <Url
            key={url._id}
            shortUrl={url.shortUrl}
            id={url._id}
            originalUrl={url.originalUrl}
            shortUrlHash={url.shortUrlHash}
            handleDelete={handleDelete}
            />
          ))}
        </tbody>
      </table>
    </div>
  )
}

export default UrlList

// vue-client/src/components/UrlList.vue
<template>
  <div>
    <p v-if="urls.length === 0">Start shortening your urls</p>
    <p v-else-if="urls.length > 0">Here are your shortened urls</p>
    <p v-show="error">{{ error }}</p>
    <table>
    <thead>
      <tr>
        <td>Original Url</td>
        <td>Shortened Url</td>
        <td>Action</td>
      </tr>
    </thead>
    <tbody>
      <Url v-for="url in urls" :key="url._id" :shortUrl="url.shortUrl" :id="url._id" :originalUrl="url.originalUrl" :shortUrlHash="url.shortUrlHash" :handleDelete="handleDelete"/>
    </tbody>
  </table>
  </div>
</template>

<script>
import Url from './Url.vue'
export default {
  props: {
    urls: {
      type: Array,
      required: true
    },
    error: {
      type: String,
      required: true
    },
    handleDelete: {
      type: Function,
      required: true
    }
  },
  components: {
    Url
  },
  name: 'UrlList',
  data: function() {
    return {

    }
  }
}
</script>

<style scoped>

</style>
