// vue-client/src/App.vue
<template>
  <div id="app">
    <h1>URL Shortener</h1>
    <UrlForm v-bind:shortenUrl="shortenUrl" />
    <UrlList v-bind:urls="urls" v-bind:error="error" v-bind:handleDelete="handleDelete" />
    <button @click="handleDeleteAll" :disabled="urls.length === 0">Delete all</button>
  </div>
</template>

<script>
import UrlList from './components/UrlList.vue'
import UrlForm from './components/UrlForm.vue'
import Axios from 'axios'

export default {
  name: 'App',
  components: {
    UrlForm,
    UrlList
  },
  data: function() {
    return {
      urls: [],
      error: ''
    }
  },
  methods: {
    shortenUrl: async function(originalUrl) {
      try {
        const res = await Axios.post('http://localhost:3000/api/url/createShortLink', { originalUrl })
        this.urls = [...this.urls, res.data]
        this.error = ''
      } catch (error) {
        this.error = error.response.data.error
      }
    },

    handleDeleteAll: async function() {
      const ans = confirm('Are you sure you want to delete all urls')
      try {
        if (ans) {
          const res = await Axios.delete('http://localhost:3000/api/url/all', {data: ''})
          alert(res.data.message)
          this.urls = []
        }
      } catch (error) {
        this.error = 'There was a problem deleting all urls'
      }
    },

    handleDelete: async function(id) {
      try {
        const ans = confirm('Are you sure want to delete this url')
        if (ans) {
          await Axios.delete(`http://localhost:3000/api/url/one/${id}`, {data: ''})
          this.urls = this.urls.filter(url => url._id !== id)
        }
      } catch (error) {
        this.error = 'There was a problem deleting the url'
      }
      console.log('handleDelete')
    }
  },
  mounted: async function() {
    try {
      const res = await Axios.get('http://localhost:3000/api/url/get_urls')
      this.urls = res.data
    } catch (error) {
      this.error = 'Oops there seems to be a problem fetching your saved urls'
    }
  },
}
</script>

<style>

</style>

// client/src/components/App.tsx
import React, { useState, useEffect } from 'react'
import Axios from 'axios'
import UrlList from './UrlList'
import UrlForm from './UrlForm'
import '../styles/App.css'

const App = () => {
  const [urls, setUrls] = useState<Array<{_id: string, shortUrl: string, originalUrl: string, shortUrlHash: string}>>([])
  const [error, setError] = useState<string>('')

  const shortenUrl = (originalUrl: string) => {
    Axios
      .post('http://localhost:3000/api/url/createShortLink', { originalUrl })
      .then((res) => {
        setUrls([...urls, res.data])
        setError('')
      })
      .catch((err) => {
        setError('There was a problem saving your URL to the database. Check your connection and try again')
      })
  }

  const handleDeleteAll = () => {
    const ans = confirm('Are you sure you want to delete all urls')
    if (ans) {
      Axios.delete('http://localhost:3000/api/url/all', {data: ''})
      .then(res => {
        setUrls([])
      })
      .catch(err => {
        setError('There was a problem deleting all urls')
      })
    }
  }

  const handleDelete = (id : string) : void => {
    const ans = confirm('Are you sure you want to delete this url')
    if (ans) {
      Axios.delete(`http://localhost:3000/api/url/one/${id}`, { data: '' })
        .then(res => {
          let updatedUrls = urls.filter(url => url._id !== id)
          setUrls([...updatedUrls])
        })
        .catch(err => {
          setError('There was a problem deleting the url')
        })
    }
  }

  const fetchUrls = async () : Promise<void> => {
    const res = await Axios.get('http://localhost:3000/api/url/get_urls')
    if (res.status === 200 || res.statusText === '  OK') {
      setUrls([...urls, res.data])
    } else {
      setError('Oops there seems to be a problem with the network.\n Check your connection and try again')
    }
  }

  useEffect(() => { 
    // const res = fetchUrls()
    Axios
      .get('http://localhost:3000/api/url/get_urls')
      .then((res) => {
        setUrls([...urls, ...res.data])
        setError('')
      })
      .catch((err) => {
        setError('Oops there seems to be a problem with the network. Check your connection and try again')
      })
  }, [])
  
  return (
    <div className='container'>
      <h1 data-testid="title">URL Shortener</h1>
      <UrlForm shortenUrl={shortenUrl} />
      <UrlList urls={urls} error={error} handleDelete={handleDelete}/>
      <button className='delete-all' onClick={handleDeleteAll}>Delete all</button>
    </div>
  )
}

export default App
